name: course-project
version: "1.0"
services:
  backend:
    container_name: backend
    build: ../backend
    ports:
      - 8080:8080
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/devschool
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ../frontend
    ports:
      - 8081:8081
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devschool
    volumes:
      - ./db_data:/db_data:rw
    networks:
      - default